package BrotatoBuildPlanner.Vista;

import BrotatoBuildPlanner.Vista.Components.PanelMenu;
import BrotatoBuildPlanner.Vista.Components.PanelBuild;
import BrotatoBuildPlanner.Controlador.BrotatoController;
import java.awt.BorderLayout;
import javax.swing.JPanel;

/**
 *
 * @author Manuel
 */
public class Window extends javax.swing.JFrame {
    
    private PanelBuild pb = new PanelBuild();
    private PanelMenu pm = new PanelMenu();
    
    private BrotatoController controlador;
    /**
     * Creates new form Window
     */
    public Window() {
        initComponents();
        setTitle("Brotato Build Planner");
        getContentPane().removeAll();
        getContentPane().add(pb);
    }

    public PanelBuild getPb() {
        return pb;
    }

    public PanelMenu getPm() {
        return pm;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.CardLayout(5, 5));

        panel.setName(""); // NOI18N

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1014, Short.MAX_VALUE)
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 710, Short.MAX_VALUE)
        );

        getContentPane().add(panel, "card2");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel panel;
    // End of variables declaration//GEN-END:variables
}
