package BrotatoBuildPlanner.Vista.Components;

import BrotatoBuildPlanner.Controlador.BrotatoController;
import BrotatoBuildPlanner.Modelo.Item.Items;
import BrotatoBuildPlanner.Vista.Renderer.Renderer;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JList;

/**
 *
 * @author Manuel
 */
public class PanelBuild extends javax.swing.JPanel {

    /**
     * Creates new form PanelBuild
     */
    public PanelBuild() {
        initComponents();
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        delimiter = new javax.swing.JLabel();
        lblAppName = new javax.swing.JLabel();
        characterScrollPane = new javax.swing.JScrollPane();
        characterList = new javax.swing.JList<>();
        itemsScrollPane = new javax.swing.JScrollPane();
        ItemList = new javax.swing.JList<>();
        lblCharacterImage = new javax.swing.JLabel();
        statPanel = new javax.swing.JPanel();
        lblStats = new javax.swing.JLabel();
        lblMaxHP = new javax.swing.JLabel();
        lblRegeneration = new javax.swing.JLabel();
        lblLifeSteal = new javax.swing.JLabel();
        lblDamage = new javax.swing.JLabel();
        lblMelee = new javax.swing.JLabel();
        lblRanged = new javax.swing.JLabel();
        lblElemental = new javax.swing.JLabel();
        lblAttackSpeed = new javax.swing.JLabel();
        lblCritChance = new javax.swing.JLabel();
        lblEngineering = new javax.swing.JLabel();
        lblRange = new javax.swing.JLabel();
        lblArmor = new javax.swing.JLabel();
        lblDodge = new javax.swing.JLabel();
        lblSpeed = new javax.swing.JLabel();
        lblLuck = new javax.swing.JLabel();
        lblHarvesting = new javax.swing.JLabel();
        btnSave = new javax.swing.JButton();
        btnLoad = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        selectedList = new javax.swing.JList<>();

        setPreferredSize(new java.awt.Dimension(1280, 1024));
        java.awt.GridBagLayout layout = new java.awt.GridBagLayout();
        layout.columnWidths = new int[] {0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0};
        layout.rowHeights = new int[] {0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0};
        layout.columnWeights = new double[] {0.0};
        layout.rowWeights = new double[] {0.0};
        setLayout(layout);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 64;
        gridBagConstraints.gridy = 64;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        add(delimiter, gridBagConstraints);

        lblAppName.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
        lblAppName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAppName.setText("Brotato Build Planner");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 28;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 20;
        gridBagConstraints.gridheight = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        add(lblAppName, gridBagConstraints);

        characterScrollPane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        characterScrollPane.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        characterScrollPane.setViewportBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        characterList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        characterList.setCellRenderer(new Renderer());
        characterList.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        characterList.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                characterListMouseMoved(evt);
            }
        });
        characterScrollPane.setViewportView(characterList);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 20;
        gridBagConstraints.gridheight = 20;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(0, 20, 20, 0);
        add(characterScrollPane, gridBagConstraints);

        itemsScrollPane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        itemsScrollPane.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        itemsScrollPane.setViewportBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        ItemList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        ItemList.setCellRenderer(new Renderer());
        itemsScrollPane.setViewportView(ItemList);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 27;
        gridBagConstraints.gridwidth = 20;
        gridBagConstraints.gridheight = 20;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(20, 20, 20, 0);
        add(itemsScrollPane, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 28;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 20;
        gridBagConstraints.gridheight = 20;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(30, 30, 30, 30);
        add(lblCharacterImage, gridBagConstraints);

        lblStats.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblStats.setText("Stats");

        lblMaxHP.setText("Max HP: 0");

        lblRegeneration.setText("HP Regeneration: 0");

        lblLifeSteal.setText("Life Steal: 0");

        lblDamage.setText("Damage: 0%");

        lblMelee.setText("Melee Damage: 0");

        lblRanged.setText("RangedDamage: 0");

        lblElemental.setText("Elemental Damage: 0");

        lblAttackSpeed.setText("Attack Speed: 0%");

        lblCritChance.setText("Crit Chance: 0%");

        lblEngineering.setText("Engineering: 0");

        lblRange.setText("Range: 0");

        lblArmor.setText("Armor: 0");

        lblDodge.setText("Dodge: 0%");

        lblSpeed.setText("Speed: 0%");

        lblLuck.setText("Luck: 0");

        lblHarvesting.setText("Harvesting: 0");

        javax.swing.GroupLayout statPanelLayout = new javax.swing.GroupLayout(statPanel);
        statPanel.setLayout(statPanelLayout);
        statPanelLayout.setHorizontalGroup(
            statPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(statPanelLayout.createSequentialGroup()
                .addGroup(statPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblStats)
                    .addComponent(lblMaxHP)
                    .addComponent(lblRegeneration)
                    .addComponent(lblLifeSteal)
                    .addComponent(lblDamage)
                    .addComponent(lblMelee)
                    .addComponent(lblRanged)
                    .addComponent(lblElemental)
                    .addComponent(lblAttackSpeed)
                    .addComponent(lblCritChance)
                    .addComponent(lblEngineering)
                    .addComponent(lblRange)
                    .addComponent(lblArmor)
                    .addComponent(lblDodge)
                    .addComponent(lblSpeed)
                    .addComponent(lblLuck)
                    .addComponent(lblHarvesting))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        statPanelLayout.setVerticalGroup(
            statPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(statPanelLayout.createSequentialGroup()
                .addComponent(lblStats)
                .addGap(18, 18, 18)
                .addComponent(lblMaxHP)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblRegeneration)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblLifeSteal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblDamage)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblMelee)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblRanged)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblElemental)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblAttackSpeed)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblCritChance)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblEngineering)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblRange)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblArmor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblDodge)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSpeed)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblLuck)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblHarvesting)
                .addGap(0, 51, Short.MAX_VALUE))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 49;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 16;
        gridBagConstraints.gridheight = 63;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(20, 0, 0, 0);
        add(statPanel, gridBagConstraints);

        btnSave.setText("Save");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 47;
        gridBagConstraints.gridy = 65;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 30);
        add(btnSave, gridBagConstraints);

        btnLoad.setText("Load");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 48;
        gridBagConstraints.gridy = 65;
        add(btnLoad, gridBagConstraints);

        btnBack.setText("Back");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 64;
        gridBagConstraints.gridy = 65;
        add(btnBack, gridBagConstraints);

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        selectedList.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        selectedList.setCellRenderer(new Renderer());
        jScrollPane1.setViewportView(selectedList);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 32;
        gridBagConstraints.gridy = 27;
        gridBagConstraints.gridwidth = 20;
        gridBagConstraints.gridheight = 20;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(20, 10, 20, 20);
        add(jScrollPane1, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void characterListMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_characterListMouseMoved
        BrotatoController.invokeTooltip(characterList, evt);
    }//GEN-LAST:event_characterListMouseMoved

    public JList<Items> getItemList() {
        return ItemList;
    }

    public JButton getBtnBack() {
        return btnBack;
    }

    public JButton getBtnLoad() {
        return btnLoad;
    }

    public JButton getBtnSave() {
        return btnSave;
    }

    public JList<Items> getCharacterList() {
        return characterList;
    }

    public JLabel getLblAppName() {
        return lblAppName;
    }

    public JLabel getLblArmor() {
        return lblArmor;
    }

    public JLabel getLblAttackSpeed() {
        return lblAttackSpeed;
    }

    public JLabel getLblCharacterImage() {
        return lblCharacterImage;
    }

    public JLabel getLblCritChance() {
        return lblCritChance;
    }

    public JLabel getLblDamage() {
        return lblDamage;
    }

    public JLabel getLblDodge() {
        return lblDodge;
    }

    public JLabel getLblElemental() {
        return lblElemental;
    }

    public JLabel getLblEngineering() {
        return lblEngineering;
    }

    public JLabel getLblHarvesting() {
        return lblHarvesting;
    }

    public JLabel getLblLifeSteal() {
        return lblLifeSteal;
    }

    public JLabel getLblLuck() {
        return lblLuck;
    }

    public JLabel getLblMaxHP() {
        return lblMaxHP;
    }

    public JLabel getLblMelee() {
        return lblMelee;
    }

    public JLabel getLblRange() {
        return lblRange;
    }

    public JLabel getLblRanged() {
        return lblRanged;
    }

    public JLabel getLblRegeneration() {
        return lblRegeneration;
    }

    public JLabel getLblSpeed() {
        return lblSpeed;
    }

    public JLabel getLblStats() {
        return lblStats;
    }

    public JList<Items> getSelectedList() {
        return selectedList;
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<Items> ItemList;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnLoad;
    private javax.swing.JButton btnSave;
    private javax.swing.JList<Items> characterList;
    private javax.swing.JScrollPane characterScrollPane;
    private javax.swing.JLabel delimiter;
    private javax.swing.JScrollPane itemsScrollPane;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAppName;
    private javax.swing.JLabel lblArmor;
    private javax.swing.JLabel lblAttackSpeed;
    private javax.swing.JLabel lblCharacterImage;
    private javax.swing.JLabel lblCritChance;
    private javax.swing.JLabel lblDamage;
    private javax.swing.JLabel lblDodge;
    private javax.swing.JLabel lblElemental;
    private javax.swing.JLabel lblEngineering;
    private javax.swing.JLabel lblHarvesting;
    private javax.swing.JLabel lblLifeSteal;
    private javax.swing.JLabel lblLuck;
    private javax.swing.JLabel lblMaxHP;
    private javax.swing.JLabel lblMelee;
    private javax.swing.JLabel lblRange;
    private javax.swing.JLabel lblRanged;
    private javax.swing.JLabel lblRegeneration;
    private javax.swing.JLabel lblSpeed;
    private javax.swing.JLabel lblStats;
    private javax.swing.JList<Items> selectedList;
    private javax.swing.JPanel statPanel;
    // End of variables declaration//GEN-END:variables
}
